export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const UPDATE_PURCHASEABLE = "UPDATE_PURCHASEABLE";
export const RESET_INGREDIENTS = "RESET_INGREDIENTS";

export const LOAD_ITEMS = "LOAD_ITEMS";
export const ITEM_LOAD_FAILED = "ITEM_LOAD_FAILED";
export const SELECTED_ITEM = "SELECTED_ITEM";

export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const COMMENT_LOAD_FAILED = "COMMENT_LOAD_FAILED";

export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const CATEGORY_LOAD_FAILED = "CATEGORY_LOAD_FAILED";
export const SELECTED_CATEGORY = "SELECTED_CATEGORY";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const ORDER_LOAD_FAILED = "ORDER_LOAD_FAILED";

export const ORDER_ITEM = "ORDER_ITEM";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
